#!/usr/bin/env bash

# shellcheck disable=SC1091
. "$(dirname -- "$0")/_/husky.sh"
. "$(dirname -- "$0")/common.sh"

npx commitlint --edit "$1" || {
  error "invalid commit message format"
  exit 1
}
